# HTTP Server
server:
  port: 16346  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel2-service
  main:
    allow-circular-references: true
  data:
    mongodb:
      host: ts-travel2-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017
swagger:
  controllerPackage: travel2.controller
