spring:
  application:
    name: ts-consign-price-service
  main:
    allow-circular-references: true
  data:
    mongodb:
      host: ts-consign-price-mongo
      database: ts
      port: 27017


# HTTP Server
server:
  port: 16110

swagger:
  controllerPackage: consignprice.controller
