server:
  port: 15678  # HTTP (Tomcat) port

spring:
  main:
    allow-circular-references: true
  application:
    name: ts-verification-code-service

swagger:
  controllerPackage: verifycode.controller
