server:
  port: 12347

spring:
  application:
    name: ts-contacts-service
  main:
    allow-circular-references: true
  data:
    mongodb:
      host: ts-contacts-mongo
      database: ts
      port: 27017

swagger:
  controllerPackage: contacts.controller
