server:
  port: 18855

spring:
  application:
    name: ts-food-map-service
  main:
    allow-circular-references: true
  data:
    mongodb:
      host: ts-food-map-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

swagger:
  controllerPackage: food.controller
