# HTTP Server
server:
  port: 12346  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel-service
  main:
    allow-circular-references: true
  data:
    mongodb:
      host: ts-travel-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017
swagger:
  controllerPackage: travel.controller
