# HTTP Server
server:
  port: 14322  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel-plan-service
  main:
    allow-circular-references: true


swagger:
  controllerPackage: travelplan.controller
