spring:
  application:
    name: ts-route-plan-service
  main:
    allow-circular-references: true

# HTTP Server
server:
  port: 14578 # HTTP (Tomcat) port


swagger:
  controllerPackage: plan.controller
