spring:
  application:
    name: ts-consign-service
  main:
    allow-circular-references: true
  data:
    mongodb:
      host: ts-consign-mongo
      database: ts
      port: 27017


# HTTP Server
server:
  port: 16111

swagger:
  controllerPackage: consign.controller
