# HTTP Server
server:
  port: 15681  # HTTP (Tomcat) port

spring:
  application:
    name: ts-ticketinfo-service
  main:
    allow-circular-references: true


swagger:
  controllerPackage: ticketinfo.controller
